export default {
  // 切换details页面的显示状态
  TOGGLE_DETAILS: "TOGGLE_DETAILS",
  // 切换购物车页面的显示状态
  TOGGLE_SHOP_CARTS: "TOGGLE_SHOP_CARTS",
  
  // 保存state
  SAVE_HEAD: "SAVE_HEAID",
  SAVE_GOODS: "SAVE_GOODS",
  SAVE_RATES: "SAVE_RATES",
  SAVE_SELLER: "SAVE_SELLER",

  // 获取数据
  FETCH_HEAD_AND_GOODS: "FETCH_HEAD_AND_GOODS",
  FETCH_RATES: "FETCH_RATES",
  FETCH_SELLER: "FETCH_SELLER",

  // 加减商品
  ADD_ITEM: "ADD_ITEM",
  DELETE_ITEM: "DELETE_ITEM",

  // 清空购物车
  CLEAR_SHOP_CART: "CLEAR_SHOP_CART",

  // 显示商品详情页面
  SHOW_DETAILS: "SHOW_DETAILS",

  //显示商品评论
  SORT_COMMENTS_INCREASE: "SORT_COMMENTS_INCREASE",
  SHOW_COMMENTS_INCREASE: "SHOW_COMMENTS_INCREASE",
  SHOW_COMMENTS_WITH_PHOTO: "SHOW_COMMENTS_WITH_PHOTO",
  SHOW_COMMENTS_IS_DP: "SHOW_COMMENTS_IS_DP"

};